use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Config {
    pub project_name: String,
    pub cloudflare_mode: String,
    pub default_share: DefaultShare,
    pub protection: Protection,
    pub services: Vec<ServiceConfig>,
    pub routes: Vec<RouteConfig>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DefaultShare {
    pub target: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Protection {
    pub expires_in: String,
    pub access_mode: String,
    pub share_token: String,
    pub warn_on_sensitive_ports: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceConfig {
    pub name: String,
    pub port: u16,
    pub role: String,
    pub framework: String,
    pub healthcheck_path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RouteConfig {
    pub profile: String,
    pub path: String,
    pub service: String,
}

impl Config {
    pub fn default_for_project(project_name: String) -> Self {
        Self {
            project_name,
            cloudflare_mode: "quick".to_string(),
            default_share: DefaultShare {
                target: "auto".to_string(),
            },
            protection: Protection::default(),
            services: Vec::new(),
            routes: Vec::new(),
        }
    }

    pub fn service_by_name(&self, name: &str) -> Option<&ServiceConfig> {
        self.services.iter().find(|service| service.name == name)
    }

    pub fn route_profile(&self, profile: &str) -> Vec<&RouteConfig> {
        self.routes
            .iter()
            .filter(|route| route.profile == profile)
            .collect()
    }
}

impl Default for Protection {
    fn default() -> Self {
        Self {
            expires_in: "1h".to_string(),
            access_mode: "token".to_string(),
            share_token: "auto".to_string(),
            warn_on_sensitive_ports: true,
        }
    }
}

pub fn config_path(project_root: &Path) -> PathBuf {
    project_root.join(".localtoglobal.yml")
}

pub fn load_config(project_root: &Path) -> Result<Option<Config>, String> {
    let path = config_path(project_root);
    if !path.exists() {
        return Ok(None);
    }

    let contents = fs::read_to_string(&path)
        .map_err(|err| format!("failed to read {}: {}", path.display(), err))?;
    parse_config(&contents).map(Some)
}

pub fn save_config(project_root: &Path, config: &Config) -> Result<(), String> {
    let path = config_path(project_root);
    let yaml = write_config(config);
    fs::write(&path, yaml).map_err(|err| format!("failed to write {}: {}", path.display(), err))
}

pub fn merge_detected_services(config: &mut Config, detected: &[ServiceConfig]) {
    let previous_default = config.default_share.target.clone();
    let mut next_services = Vec::new();

    for service in &config.services {
        if !is_autogenerated_service(service) {
            next_services.push(service.clone());
        }
    }

    for service in detected {
        if let Some(existing) = next_services.iter_mut().find(|candidate| candidate.port == service.port) {
            let preserved_name = existing.name.clone();
            *existing = service.clone();
            if !is_autogenerated_name(&preserved_name) {
                existing.name = preserved_name;
            }
            continue;
        }

        if next_services.iter().all(|candidate| candidate.name != service.name) {
            next_services.push(service.clone());
        }
    }

    config.services = next_services;

    let default_is_valid = config
        .services
        .iter()
        .any(|service| service.name == previous_default);
    if previous_default == "auto" || !default_is_valid {
        config.default_share.target = "auto".to_string();
    }

    if config.default_share.target == "auto" {
        if let Some(frontend) = config.services.iter().find(|service| service.role == "frontend") {
            config.default_share.target = frontend.name.clone();
        } else if let Some(first) = config.services.first() {
            config.default_share.target = first.name.clone();
        }
    }
}

fn is_autogenerated_service(service: &ServiceConfig) -> bool {
    is_autogenerated_name(&service.name)
}

fn is_autogenerated_name(name: &str) -> bool {
    name.starts_with("service-") || name.starts_with("app-")
}

pub fn generate_default_routes(config: &mut Config) {
    if !config.routes.is_empty() {
        return;
    }

    if let Some(frontend) = config.services.iter().find(|service| service.role == "frontend") {
        config.routes.push(RouteConfig {
            profile: "default".to_string(),
            path: "/".to_string(),
            service: frontend.name.clone(),
        });
    }

    if let Some(api) = config.services.iter().find(|service| service.role == "api") {
        config.routes.push(RouteConfig {
            profile: "default".to_string(),
            path: "/api".to_string(),
            service: api.name.clone(),
        });
    }

    if let Some(docs) = config.services.iter().find(|service| service.role == "docs") {
        config.routes.push(RouteConfig {
            profile: "default".to_string(),
            path: "/docs".to_string(),
            service: docs.name.clone(),
        });
    }
}

pub fn parse_config(input: &str) -> Result<Config, String> {
    let mut config = Config::default_for_project("localtoglobal".to_string());
    let lines: Vec<&str> = input.lines().collect();
    let mut index = 0usize;

    while index < lines.len() {
        let raw = lines[index];
        let line = raw.trim_end();
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            index += 1;
            continue;
        }

        if let Some(value) = trimmed.strip_prefix("project_name:") {
            config.project_name = unquote(value.trim());
            index += 1;
            continue;
        }
        if let Some(value) = trimmed.strip_prefix("cloudflare_mode:") {
            config.cloudflare_mode = unquote(value.trim());
            index += 1;
            continue;
        }

        if trimmed == "default_share:" {
            index += 1;
            while index < lines.len() {
                let child = lines[index];
                if indentation(child) < 2 {
                    break;
                }
                let child_trimmed = child.trim();
                if let Some(value) = child_trimmed.strip_prefix("target:") {
                    config.default_share.target = unquote(value.trim());
                }
                index += 1;
            }
            continue;
        }

        if trimmed == "protection:" {
            index += 1;
            while index < lines.len() {
                let child = lines[index];
                if indentation(child) < 2 {
                    break;
                }
                let child_trimmed = child.trim();
                if let Some(value) = child_trimmed.strip_prefix("expires_in:") {
                    config.protection.expires_in = unquote(value.trim());
                } else if let Some(value) = child_trimmed.strip_prefix("access_mode:") {
                    config.protection.access_mode = unquote(value.trim());
                } else if let Some(value) = child_trimmed.strip_prefix("share_token:") {
                    config.protection.share_token = unquote(value.trim());
                } else if let Some(value) = child_trimmed.strip_prefix("warn_on_sensitive_ports:") {
                    config.protection.warn_on_sensitive_ports = parse_bool(value.trim())?;
                }
                index += 1;
            }
            continue;
        }

        if trimmed == "services:" {
            index += 1;
            while index < lines.len() {
                if indentation(lines[index]) < 2 {
                    break;
                }
                if !lines[index].trim_start().starts_with('-') {
                    index += 1;
                    continue;
                }
                let mut service = ServiceConfig {
                    name: String::new(),
                    port: 0,
                    role: "unknown".to_string(),
                    framework: "unknown".to_string(),
                    healthcheck_path: "/".to_string(),
                };
                let mut first_line = true;
                while index < lines.len() {
                    let child = lines[index];
                    if first_line {
                        let payload = child.trim_start().trim_start_matches('-').trim();
                        if !payload.is_empty() {
                            assign_service_value(&mut service, payload)?;
                        }
                        first_line = false;
                        index += 1;
                        continue;
                    }
                    if indentation(child) < 4 {
                        break;
                    }
                    assign_service_value(&mut service, child.trim())?;
                    index += 1;
                }
                if !service.name.is_empty() && service.port > 0 {
                    config.services.push(service);
                }
            }
            continue;
        }

        if trimmed == "routes:" {
            index += 1;
            while index < lines.len() {
                if indentation(lines[index]) < 2 {
                    break;
                }
                if !lines[index].trim_start().starts_with('-') {
                    index += 1;
                    continue;
                }
                let mut route = RouteConfig {
                    profile: "default".to_string(),
                    path: "/".to_string(),
                    service: String::new(),
                };
                let mut first_line = true;
                while index < lines.len() {
                    let child = lines[index];
                    if first_line {
                        let payload = child.trim_start().trim_start_matches('-').trim();
                        if !payload.is_empty() {
                            assign_route_value(&mut route, payload)?;
                        }
                        first_line = false;
                        index += 1;
                        continue;
                    }
                    if indentation(child) < 4 {
                        break;
                    }
                    assign_route_value(&mut route, child.trim())?;
                    index += 1;
                }
                if !route.service.is_empty() {
                    config.routes.push(route);
                }
            }
            continue;
        }

        return Err(format!("unsupported config line: {}", trimmed));
    }

    Ok(config)
}

pub fn write_config(config: &Config) -> String {
    let mut output = String::new();
    writeln!(&mut output, "project_name: {}", quote(&config.project_name)).unwrap();
    writeln!(
        &mut output,
        "cloudflare_mode: {}",
        quote(&config.cloudflare_mode)
    )
    .unwrap();
    writeln!(&mut output, "default_share:").unwrap();
    writeln!(
        &mut output,
        "  target: {}",
        quote(&config.default_share.target)
    )
    .unwrap();
    writeln!(&mut output, "protection:").unwrap();
    writeln!(
        &mut output,
        "  expires_in: {}",
        quote(&config.protection.expires_in)
    )
    .unwrap();
    writeln!(
        &mut output,
        "  access_mode: {}",
        quote(&config.protection.access_mode)
    )
    .unwrap();
    writeln!(
        &mut output,
        "  share_token: {}",
        quote(&config.protection.share_token)
    )
    .unwrap();
    writeln!(
        &mut output,
        "  warn_on_sensitive_ports: {}",
        config.protection.warn_on_sensitive_ports
    )
    .unwrap();
    writeln!(&mut output, "services:").unwrap();
    for service in &config.services {
        writeln!(&mut output, "  - name: {}", quote(&service.name)).unwrap();
        writeln!(&mut output, "    port: {}", service.port).unwrap();
        writeln!(&mut output, "    role: {}", quote(&service.role)).unwrap();
        writeln!(
            &mut output,
            "    framework: {}",
            quote(&service.framework)
        )
        .unwrap();
        writeln!(
            &mut output,
            "    healthcheck_path: {}",
            quote(&service.healthcheck_path)
        )
        .unwrap();
    }
    writeln!(&mut output, "routes:").unwrap();
    for route in &config.routes {
        writeln!(&mut output, "  - profile: {}", quote(&route.profile)).unwrap();
        writeln!(&mut output, "    path: {}", quote(&route.path)).unwrap();
        writeln!(&mut output, "    service: {}", quote(&route.service)).unwrap();
    }
    output
}

fn assign_service_value(service: &mut ServiceConfig, line: &str) -> Result<(), String> {
    if let Some(value) = line.strip_prefix("name:") {
        service.name = unquote(value.trim());
    } else if let Some(value) = line.strip_prefix("port:") {
        service.port = value
            .trim()
            .parse::<u16>()
            .map_err(|err| format!("invalid service port: {}", err))?;
    } else if let Some(value) = line.strip_prefix("role:") {
        service.role = unquote(value.trim());
    } else if let Some(value) = line.strip_prefix("framework:") {
        service.framework = unquote(value.trim());
    } else if let Some(value) = line.strip_prefix("healthcheck_path:") {
        service.healthcheck_path = unquote(value.trim());
    }
    Ok(())
}

fn assign_route_value(route: &mut RouteConfig, line: &str) -> Result<(), String> {
    if let Some(value) = line.strip_prefix("profile:") {
        route.profile = unquote(value.trim());
    } else if let Some(value) = line.strip_prefix("path:") {
        route.path = unquote(value.trim());
    } else if let Some(value) = line.strip_prefix("service:") {
        route.service = unquote(value.trim());
    } else {
        return Err(format!("unsupported route field: {}", line));
    }
    Ok(())
}

fn parse_bool(value: &str) -> Result<bool, String> {
    match value {
        "true" => Ok(true),
        "false" => Ok(false),
        other => Err(format!("invalid boolean value: {}", other)),
    }
}

fn indentation(line: &str) -> usize {
    line.chars().take_while(|ch| *ch == ' ').count()
}

fn unquote(value: &str) -> String {
    if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
        value[1..value.len() - 1]
            .replace("\\\"", "\"")
            .replace("\\\\", "\\")
    } else {
        value.to_string()
    }
}

fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_written_config() {
        let mut config = Config::default_for_project("demo".to_string());
        config.services.push(ServiceConfig {
            name: "frontend".to_string(),
            port: 3000,
            role: "frontend".to_string(),
            framework: "vite".to_string(),
            healthcheck_path: "/".to_string(),
        });
        config.routes.push(RouteConfig {
            profile: "default".to_string(),
            path: "/".to_string(),
            service: "frontend".to_string(),
        });

        let yaml = write_config(&config);
        let parsed = parse_config(&yaml).unwrap();
        assert_eq!(parsed, config);
    }
}
